### ISSUE TITLE
example in readme

### ISSUE THREAD

**Issue by GliderGeek** [yondemon/justwatch_chrome#4]
nice work! i was looking for something like this and stumbled upon your work. for a quick check if this is indeed what i'm looking for, a screenshot would be very nice. in my case i'm particularly interested to see the imdb integration. would you be willing to add this?

**Comment by yondemon** [comment]
The extension attaches this box to the DOM as the last element in the target block
![image](https://user-images.githubusercontent.com/1371816/144068781-ca30118a-d5fe-45d7-a6e3-fdc60900720e.png)
