### ISSUE TITLE
Can you add Italy?

### ISSUE THREAD

**Issue by simonechecchia** [yondemon/justwatch_chrome#5]

**Comment by yondemon** [comment]
Added all available countries in [last commit.](https://github.com/yondemon/justwatch_chrome/commit/62b9c2e4942a8d0a531ee3f361c10a527ea674ac)

* Algeria
* Argentina
* Australia
* Austria
* Bahamas
* Bahrain
* Barbados
* Belgium
* Bermuda
* Bolivia
* Brasil
* Bulgaria
* Canada
* Chile
* Colombia
* Costa Rica
* Croatia
* Czech Republic
* Denmark
* Deutschland
* Dominican Republic
* Ecuador
* Egypt
* El Salvador
* España
* Estonia
* Finland
* France
* French Guiana
* Gibraltar
* Greece
* Guatemala
* Honduras
* Hong Kong
* Hungary
* Iceland
* India
* Indonesia
* Ireland
* Italia
* Jamaica
* Japan
* Jordan
* Kuwait
* Latvia
* Libya
* Liechtenstein
* Lithuania
* Malaysia
* Mexico
* Moldova
* Monaco
* Morocco
* Netherlands
* New Zealand
* Norway
* Oman
* Panama
* Paraguay
* Peru
* Philippines
* Poland
* Portugal
* Qatar
* Romania
* Russia
* San Marino
* Saudi Arabia
* Singapore
* Slovakia
* South Africa
* South Korea
* Sweden
* Switzerland
* Taiwan
* Thailand
* Tunisia
* Turkey
* United Arab Emirates
* United Kingdom
* USA
* Uruguay
* Venezuela
* Yemen

Some logos for providers are not shown (Work in progress).
