### ISSUE TITLE
Error in chrome

### ISSUE THREAD

**Issue by blackholeintothewild** [yondemon/justwatch_chrome#7]
Not sure if you're still working on this, but I am getting an error when I try to use it: Uncaught (in promise) SyntaxError: Unexpected non-whitespace character after JSON at position 4 (line 1 column 5)

Context
background.js
Stack Trace
background.js:1 (anonymous function)

const API_DOMAIN = 'apis.justwatch.com';
var debug = false;

chrome.runtime.onMessage.addListener( (message, sender, callback) => {
  
  if(debug) console.log(message);

  // chrome.runtime.onMessage.removeListener(event); // cleaning, just call once.
  
  if (message.type == "fetchAPI") {
    var data = message.data;
    
    // https://apis.justwatch.com/content/titles/es_ES/popular
    const url = `https://${API_DOMAIN}/content/titles/${data.localization}/popular`;
    if (debug) console.log(url);
    
    var query = {"query":data.title};
    if(typeof data.type != 'undefined'){
      query.content_types = [data.type];
    }
    if(debug) console.log(query);

    fetch( url, {
      method: 'post',
      headers: {
        "Content-Type": "application/json; charset=UTF-8",
        // 'User-Agent': 'JustWatch unofficial chrome extension (github.com/yondemon/justwatch_chrome/)'
      },
      body: JSON.stringify(query)
    })
    .then((response) => {
      response.json().then((data) => {
        if(debug) console.log(data);
          
        if (data.total_results > 0) {
          if(debug) console.log(data.total_results + ' results');
          if(debug) console.log(data);
          
          callback(data);
        }
      });
    })
  }
  
  if (message.type == "fetchProvidersAPI") {
    var data = message.data;
    
    // https://apis.justwatch.com/content/providers/locale/es_ES"
    const url = `https://${API_DOMAIN}/content/providers/locale/${data.localization}`;
    if (debug) console.log(url);
    
    fetch(url, {
      headers: {
        "Content-Type": "application/json; charset=UTF-8",
        // 'User-Agent': 'JustWatch unofficial chrome extension (github.com/yondemon/justwatch_chrome/)'
      }
    }).then((response) => {
      response.json().then((data) => {
        if(debug) console.log(data);
  
        if (data.length > 0) {
          if(debug) console.log(`${data.length} providers`);
          callback(data);
        }  
      });
    });
  }

  return true;
});

**Comment by yondemon** [comment]
It looks Justwatch has deleted the free api at apis.justwatch.com, so this script only retrieves a 404.
This is the end of this project.

Meanwhile, most of the sites are implementing the Justwatch Widget so this plugin is not useful anymore.
